### ISSUE TITLE
App does not work: account not registered

### ISSUE THREAD

**Issue by AbomineveHomidasNave** [KnightVisionApp/KnightVisionBeta#6]
When visiting the playstore store and installing the app I was informed that my smartphone was not compatible (Nokia C20). It was suggested that I install it on my other smartphone, a Redmi Note 7 (which is older). So I ran the app on Redmi and installed it in open, they asked me to authorize access to my Lichess account (AbomineveHomidasNave) and I did. Then the app came back telling me that I hadn't been registered for the Beta Test!!???
Too? Both smartphones are registered to my Gmail account, the same one I signed up for in the Beta Test program.

**Comment by mfalt** [comment]
Did you get an email with a link to sign up for the beta?
We are continually sending out invite links to the users who have entered their email on the website. Only those users who have registered through that link are currently able to use the app currently.

**Comment by AbomineveHomidasNave** [comment]
Yes! See:
"Em sáb., 22 de jan. de 2022 às 10:32, Niklas Silfverström <
***@***.***> escreveu:
>
> Hi!
>
> I’m emailing you because you’ve signed up to the Knightvision Beta.
> Knightvision is an app that lets you record a chess game using only a
> mobile phone and a tripod, and then save it as pgn.
>
> We’re finally ready to let real users into the Beta. You’re one of the
> first people we’re inviting and we hope that you will enjoy the beta. I
> just want to warn you that the program might not work correctly when you’re
> trying it out, but we’re working very hard to get everything stable and
> running as smoothly as possible and we will try and resolve any issues you
> might run into as soon as possible.
>
> We would be very happy if you returned any feedback to us in one of two
> ways:
>
> Email: ***@***.***
>
> Bug-tracker: https://github.com/KnightVisionApp/KnightVisionBeta/issues
>
> You can download the app on Googles Playstore (Currently only on Android)
>
> https://play.google.com/store/apps/details?id=com.knightvision
>
> After you’ve downloaded the app you can activate your account on the
> following link, which will prompt you to give Knightvision partial access
> to your lichess-account. All your recorded games in Knightvision will then
> be imported directly to Lichess.
>
> The general usage of the app is as follows:
>
>    1.
>
>    Login with lichess
>    2.
>
>    Press the camera button
>    3.
>
>    Press the cogwheel and enter names of the players
>    4.
>
>    Ensure that the camera sees the whole chessboard, from the side and
>    slightly above, and press the camera button to start tracking the game.
>    5.
>
>    Wait for “Board detection completed” and start playing!
>    6.
>
>    Once the game is over, press the stop button and report who won,
>    before moving the pieces.
>    7.
>
>    The full game is now available in the app and on your Lichess account
>    under “Imported Games”
>
>
> It is also possible to view your games and track them live on
> https://app.knightvision.io/. However, the page is currently under
> development with a temporary user interface.
>
>
> LINK DELETED
>
> Thank you again for participating in the Beta!
>
> Kind regards"
>

Em sáb., 22 de jan. de 2022 às 17:53, Mattias Fält ***@***.***>
escreveu:

**Comment by mfalt** [comment]
It doesn't seem that you actually clicked that link and authenticated to activate it?

I had to disable it now since you posted it publicly. We will try to resend it tomorrow.

**Comment by AbomineveHomidasNave** [comment]
Oh!! Very sorry! She didn't know the link was individual.

Em sáb., 22 de jan. de 2022 às 21:47, Mattias Fält ***@***.***>
escreveu:
